name: comp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pytorch=2.1

  # Core scientific stack
  - numpy
  - pandas
  - scipy
  - scikit-learn

  # Utilities
  - tqdm
  - matplotlib
  - seaborn
  - pyyaml
  - jupyter
  - ipykernel

  # Install pip packages
  - pip:
    - rna-fm
    - transformers

