name: uni_rna
modality: RNA
Dataset: fungal_expression #  'mrna_stability', 'ecoli_proteins', 'cov_vaccine_degradation', 'fungal_expression'
batch_size: 32
epochs: 500
max_len: 3000 # max length of the sequence
projection_dim: 600 # dimension of the projection head
embedding_dim: 640 # dimension of the embedding