name: uni_protein
modality: Protein
batch_size: 32
epochs: 500
max_len: 1024 # max length of the sequence
projection_dim: 600 # dimension of the projection head
embedding_dim: 640 # dimension of the embedding